apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recotem.fullname" . }}-config
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.config.debug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}
  CELERY_BROKER_URL: "redis://{{ include "recotem.redisHost" . }}:{{ .Values.redis.port }}/{{ .Values.config.celeryBrokerDb }}"
  CACHE_REDIS_URL: "redis://{{ include "recotem.redisHost" . }}:{{ .Values.redis.port }}/{{ .Values.config.cacheRedisDb }}"
  CACHE_KEY_PREFIX: {{ .Values.config.cacheKeyPrefix | quote }}
  MODEL_CACHE_SIZE: {{ .Values.config.modelCacheSize | quote }}
  CELERY_TASK_TIME_LIMIT: {{ .Values.config.celeryTaskTimeLimit | quote }}
  CELERY_TASK_SOFT_TIME_LIMIT: {{ .Values.config.celeryTaskSoftTimeLimit | quote }}
  THROTTLE_ANON_RATE: {{ .Values.config.throttleAnonRate | quote }}
  THROTTLE_USER_RATE: {{ .Values.config.throttleUserRate | quote }}
  THROTTLE_LOGIN_RATE: {{ .Values.config.throttleLoginRate | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.config.djangoLogLevel | quote }}
  CELERY_LOG_LEVEL: {{ .Values.config.celeryLogLevel | quote }}
  MODEL_EVENTS_REDIS_URL: "redis://{{ include "recotem.redisHost" . }}:{{ .Values.redis.port }}/{{ .Values.config.modelEventsRedisDb }}"
  CELERY_BEAT_SCHEDULER: "django_celery_beat.schedulers:DatabaseScheduler"
  INFERENCE_MAX_LOADED_MODELS: {{ .Values.config.inferenceMaxLoadedModels | quote }}
  INFERENCE_RATE_LIMIT: {{ .Values.config.inferenceRateLimit | quote }}
  INFERENCE_AUTO_RECORD_IMPRESSIONS: {{ .Values.config.inferenceAutoRecordImpressions | quote }}
