apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recotem.fullname" . }}-beat
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "recotem.beatSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recotem.beatSelectorLabels" . | nindent 8 }}
    spec:
      {{- include "recotem.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "recotem.fullname" .) }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: beat
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command: ["celery", "-A", "recotem", "beat", "--loglevel=INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
          envFrom:
            - configMapRef:
                name: {{ include "recotem.fullname" . }}-config
            - secretRef:
                name: {{ include "recotem.fullname" . }}-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "recotem.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
