apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recotem.fullname" . }}-worker
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "recotem.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recotem.workerSelectorLabels" . | nindent 8 }}
    spec:
      {{- include "recotem.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: worker
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          command: ["celery", "-A", "recotem", "worker", "--loglevel=INFO"]
          envFrom:
            - configMapRef:
                name: {{ include "recotem.fullname" . }}-config
            - secretRef:
                name: {{ include "recotem.fullname" . }}-secret
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "recotem.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
