{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recotem.fullname" . }}-backend
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "recotem.backendSelectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recotem.fullname" . }}-worker
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.worker.minAvailable }}
  selector:
    matchLabels:
      {{- include "recotem.workerSelectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recotem.fullname" . }}-proxy
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  minAvailable: {{ .Values.podDisruptionBudget.proxy.minAvailable }}
  selector:
    matchLabels:
      {{- include "recotem.proxySelectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recotem.fullname" . }}-inference
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
spec:
  minAvailable: {{ .Values.podDisruptionBudget.inference.minAvailable }}
  selector:
    matchLabels:
      {{- include "recotem.inferenceSelectorLabels" . | nindent 6 }}
{{- end }}
