{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recotem.fullname" . }}-data
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.staticFiles.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recotem.fullname" . }}-static
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.staticFiles.accessModes | nindent 4 }}
  {{- if .Values.persistence.staticFiles.storageClass }}
  storageClassName: {{ .Values.persistence.staticFiles.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.staticFiles.size }}
{{- end }}
