apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recotem.fullname" . }}-secret
  labels:
    {{- include "recotem.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.defaultAdminPassword | b64enc | quote }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
